// compile Nyxal into SINGLE standalone bun binaries
//
// usage:
//   bun scripts/compile.ts                                      # native host build
//   bun scripts/compile.ts bun-linux-x64                        # one cross target
//   bun scripts/compile.ts bun-linux-x64 bun-windows-x64 ...    # several at once
//
// targets: bun-windows-x64 | bun-linux-x64 | bun-linux-arm64 | bun-linux-arm64-musl
//          bun-darwin-arm64 | bun-darwin-x64
//
// web build + manifest generation happen ONCE; each target is then compiled.
// output -> ./build/nyxal[.exe] (native) or ./build/nyxal-<target>[.exe] (cross).
//
// note: --bytecode is platform-specific, so it is only added for native builds.
// cross-compiled targets skip it to avoid shipping a binary that won't start.
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, relative, resolve, sep } from "node:path";
import { spawnSync } from "node:child_process";

const ROOT = resolve(import.meta.dirname, "..");
const BUILD_DIR = join(ROOT, "build");
const MANIFEST = join(ROOT, "server", "embeddedManifest.gen.ts");
const STUB = readFileSync(MANIFEST, "utf8");

const targets = process.argv.slice(2);

function outfileFor(t: string | undefined): string {
  if (!t) return process.platform === "win32" ? "nyxal.exe" : "nyxal";
  const name = t.replace(/^bun-/, "");
  return name.includes("windows") ? `nyxal-${name}.exe` : `nyxal-${name}`;
}

function restoreStub(): void {
  writeFileSync(MANIFEST, STUB);
}

function run(cmd: string, args: string[], label: string): void {
  console.log(`\n[${label}] ${cmd} ${args.join(" ")}`);
  const res = spawnSync(cmd, args, {
    stdio: "inherit",
    cwd: ROOT,
    shell: process.platform === "win32",
  });
  if (res.status !== 0) {
    console.error(`[${label}] failed (exit ${res.status})`);
    restoreStub();
    process.exit(res.status ?? 1);
  }
}

function walk(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(full));
    else out.push(full);
  }
  return out.sort();
}

function webUrlFor(absPath: string): string {
  const rel = relative(join(ROOT, "web", "dist"), absPath).split(sep).join("/");
  return rel === "index.html" ? "/" : `/${rel}`;
}

let binName = outfileFor(targets[0]);
const built: string[] = [];
try {
  run("bun", ["run", "build"], "web build");

  const webFiles = walk(join(ROOT, "web", "dist"));
  const migFiles = walk(join(ROOT, "server", "db", "migrations"));
  console.log(`\n[manifest] ${webFiles.length} web files, ${migFiles.length} migration files`);

  const lines: string[] = [
    "// @ts-nocheck",
    "// AUTO-GENERATED by scripts/compile.ts at compile time. Do not edit by hand.",
    "// The committed version of this file is an empty stub; this content is embedded",
    "// into the binary and the stub is restored right after.",
    "",
  ];

  let idx = 0;
  const webEntries: string[] = [];
  for (const f of webFiles) {
    const imp = `_${idx++}`;
    const rel = relative(join(ROOT, "server"), f).split(sep).join("/");
    lines.push(`import ${imp} from "./${rel}" with { type: "file" };`);
    webEntries.push(`  { url: ${JSON.stringify(webUrlFor(f))}, bunPath: ${imp} },`);
  }

  const migEntries: string[] = [];
  for (const f of migFiles) {
    const imp = `_${idx++}`;
    const rel = relative(join(ROOT, "server"), f).split(sep).join("/");
    const migRel = relative(join(ROOT, "server", "db", "migrations"), f).split(sep).join("/");
    lines.push(`import ${imp} from "./${rel}" with { type: "file" };`);
    migEntries.push(`  { relPath: ${JSON.stringify(migRel)}, bunPath: ${imp} },`);
  }

  lines.push("");
  lines.push("export const EMBEDDED_WEB: Array<{ url: string; bunPath: string }> = [");
  lines.push(...webEntries);
  lines.push("];");
  lines.push("");
  lines.push("export const EMBEDDED_MIGRATIONS: Array<{ relPath: string; bunPath: string }> = [");
  lines.push(...migEntries);
  lines.push("];");
  lines.push("");

  writeFileSync(MANIFEST, lines.join("\n"));

  // 3. compile each target (or the native host build if none given). the
  // manifest stays active across all compiles and is restored in finally.
  mkdirSync(BUILD_DIR, { recursive: true });
  const buildList = targets.length > 0 ? targets : [undefined];
  for (const t of buildList) {
    binName = outfileFor(t);
    const binPath = join(BUILD_DIR, binName);
    const compileArgs = [
      "build", "server/index.ts",
      "--compile",
      "--minify",
      "--asset-naming=[name].[ext]",
      "--define", "__COMPILED__=true",
      "--outfile", binPath,
    ];
    if (t) {
      compileArgs.push("--target", t);
    } else {
      compileArgs.push("--bytecode"); // platform-specific, native only
    }
    run("bun", compileArgs, `compile${t ? " " + t : ""}`);
    built.push(binName);
  }
} finally {
  restoreStub();
}

console.log(`\n done. ${built.length} binary/built -> build/:`);
for (const b of built) console.log(`   - build/${b}`);
